"""Export the 340 minimal-periodic frontier torus certificates as
lean-flocq/LeanFlocq/AnyK3DPeriodicCerts.lean (M4-C2 data).

Order follows anyk3d_frontier.json's minPeriodic list (indices line up
with the frontier). Grids are packed as base-24 numerals with position
(x*b + y)*c + z (z-fastest — verified 40/40 against the T2E tables by
anyk3d_cert_export's convention check, matching arena2's cell order).

Lean-side validation: `periodic_certs_valid` (native_decide over
rect3OK) in AnyK3DPeriodicValid.lean — the Python side is NOT trusted.
"""
import json

frontier = json.load(open("anyk3d_frontier.json"))
certs = json.load(open("anyk3d_periodic_certs.json"))

minp = frontier["minPeriodic"]
assert len(minp) == 340, len(minp)
assert set(map(str, minp)) == set(certs.keys()), "cert/frontier mask mismatch"

dims = []
grids = []
for m in minp:
    cert = certs[str(m)]
    a, b, c = cert["dims"]
    grid = cert["grid"]
    assert len(grid) == a * b * c
    assert all(0 <= o < 24 for o in grid)
    num = 0
    for i, o in enumerate(grid):
        num += o * 24 ** i
    dims.append((a, b, c))
    grids.append(num)

def arr(name, rows, per_row=1):
    body = ",\n  ".join(", ".join(r) for r in rows)
    return f"def {name} := #[\n  {body}\n]\n"

out = f"""/- AUTO-GENERATED by monotile/anyk3d_cert_export.py from
   monotile/anyk3d_periodic_certs.json + anyk3d_frontier.json.
   Do not edit by hand.

   The 340 minimal-periodic frontier masks with their rectangular-torus
   certificates. certGrids[i] packs the a×b×c orientation grid (entries
   Fin 24) as a base-24 numeral, digit (x*b + y)*c + z = orientation at
   torus cell (x, y, z) — z-fastest, matching AnyK3D.gLet3. -/

namespace AnyK3D

{arr("minPeriodic", [[str(m)] for m in minp])}
{arr("certDims", [[f"({a}, {b}, {c})"] for a, b, c in dims])}
{arr("certGrids", [[str(g)] for g in grids])}
end AnyK3D
"""
path = "../lean-flocq/LeanFlocq/AnyK3DPeriodicCerts.lean"
with open(path, "w") as f:
    f.write(out)
print(f"wrote {path}: {len(minp)} certs, "
      f"max grid digits {max(len(str(g)) for g in grids)}")
