"""Export anyk2d_certtable.json as lean-flocq/LeanFlocq/AnyK2DCerts.lean.

Index = held-bit number (bit i = equation EQS[i] held, EQS in triangular
order [(0,0),(0,1),(0,2),(0,3),(1,1),(1,2),(1,3),(2,2),(2,3),(3,3)] —
matching Lean's pairIdx). Grids encoded base-4: digit (x*b+y) = grid[x*b+y].
"""
import json

T = json.load(open("anyk2d_certtable.json"))
entries = []
for bits in range(1024):
    v = T[str(bits)]
    if v["cert"] == "empty6":
        entries.append(f".empty {v['w']} {v['h']}")
    else:
        a, b, grid = v["a"], v["d"], v["grid"]
        n = sum(g * 4 ** i for i, g in enumerate(grid))
        entries.append(f".rect {a} {b} {n}")

rows = [", ".join(entries[i:i + 8]) for i in range(0, 1024, 8)]
body = ",\n  ".join(rows)
out = f"""/- AUTO-GENERATED by monotile/anyk2d_lean_export.py from
   monotile/anyk2d_certtable.json — do not edit by hand.

   certArr[n] = certificate for the relation of held-equation set n
   (bit i of n = equation i held, triangular pair order). 331 empty-box +
   693 rectangular-torus certificates. -/

namespace AnyK2D

/-- A certificate: either "no w×h box tiling exists" (⟹ SFT empty) or an
explicit a×b rectangular torus tiling, grid base-4-encoded with digit
(x*b+y) = the orientation at torus cell (x, y). -/
inductive CertData where
  | empty (w h : Nat)
  | rect (a b : Nat) (grid : Nat)

def certArr : Array CertData := #[
  {body}
]

end AnyK2D
"""
path = "../lean-flocq/LeanFlocq/AnyK2DCerts.lean"
with open(path, "w") as f:
    f.write(out)
print(f"wrote {path}: {len(entries)} entries")
