"""Export the 3D geometry tables as lean-flocq/LeanFlocq/AnyK3DGeom.lean.

From faceeq3d's validated derivation (reconstruction 200/200 vs the real
arena): for every triple (ax, o1, o2) the compat condition is the face
equation E(faceA, faceB, tau). Tables exported flat, triple index
t = ax*576 + o1*24 + o2; tau coded 0..7 as sw*4 + (s1<0)*2 + (s2<0).

Also the 84 normalized equations (g, h, tau) in faceeq3d.EQS order, and
the triple -> equation index map.
"""
import json

from faceeq3d import EQS, EQ_IDX, EQ_OF, TRIPLES, eq_norm

def tau_code(tau):
    sw, s1, s2 = tau
    return sw * 4 + (2 if s1 < 0 else 0) + (1 if s2 < 0 else 0)

fa, fb, tc, ei = [], [], [], []
for ax in range(3):
    for o1 in range(24):
        for o2 in range(24):
            g, h, tau = EQ_OF[(ax, o1, o2)]
            fa.append(g)
            fb.append(h)
            tc.append(tau_code(tau))
            ei.append(EQ_IDX[eq_norm(EQ_OF[(ax, o1, o2)])])

eg = [e[0] for e in EQS]
eh = [e[1] for e in EQS]
et = [tau_code(e[2]) for e in EQS]

def arr(name, xs, ty="Nat"):
    rows = [", ".join(map(str, xs[i:i + 24])) for i in range(0, len(xs), 24)]
    body = ",\n  ".join(rows)
    return f"def {name} : Array {ty} := #[\n  {body}\n]\n"

out = f"""/- AUTO-GENERATED by monotile/anyk3d_lean_export.py from the faceeq3d
   derivation (reconstruction-validated 200/200 against arena2's compat
   tables). Do not edit by hand.

   Triple index t = ax*576 + o1*24 + o2 (ax : Fin 3, o : Fin 24).
   tau code = swap*4 + (s1 negative)*2 + (s2 negative)*1.
   Equations: the 84 normalized face equations, faceeq3d.EQS order. -/

namespace AnyK3D

{arr("tFaceA", fa)}
{arr("tFaceB", fb)}
{arr("tTau", tc)}
{arr("tEq", ei)}
{arr("eqFaceA", eg)}
{arr("eqFaceB", eh)}
{arr("eqTau", et)}
end AnyK3D
"""
path = "../lean-flocq/LeanFlocq/AnyK3DGeom.lean"
with open(path, "w") as f:
    f.write(out)
print(f"wrote {path}: {len(fa)} triples, {len(eg)} equations")
