"""Emit the Lean data file for the color empty frontier + inheritance.

Reads color_empty_frontier.json (frontier masks + inheritance map,
written by gen_color_empty_certs.py) and the verdict tiers, and writes
../lean-flocq/LeanFlocq/AnyK3DColorEmptyData.lean:

  colorFrontierJobs  : Array (Nat × Nat × Nat × Nat)   -- (mask, w, h, d)
  colorInheritance   : Array (Nat × Nat)  -- (profile mask, frontier job idx)

Sub-array split to bound elaborator recursion (like the density chunks).

Run:  ./runpy.sh color_empty_lean_export.py
"""
import json
import os

ROOT = '/home/bepis/prog/verus-cad/monotile'


def subarrays(name, ty, rows, sub=1000):
    parts = []
    subs = [rows[k:k + sub] for k in range(0, len(rows), sub)]
    for si, chunk in enumerate(subs):
        parts.append(f"def {name}_{si} : {ty} := #[\n"
                     + ",\n".join(chunk) + "\n]\n")
    names = " ++ ".join(f"{name}_{si}" for si in range(len(subs)))
    return "\n".join(parts), names


def main():
    d = json.load(open(f'{ROOT}/color_empty_frontier.json'))
    frontier = d['frontier']
    inheritance = d['inheritance']

    kills = set(k['i'] for k in json.load(
        open(f'{ROOT}/color_density_kills.json')))
    v = {}
    for line in open(f'{ROOT}/classify_color.jsonl'):
        r = json.loads(line)
        v[r['i']] = r['verdict']
    canon = json.load(open(f'{ROOT}/color3d_canonical.json'))['canonical']
    TIER = {'empty3': 3, 'empty5': 5, 'empty6': 6, 'empty7': 7}
    masks = {}
    for i, ver in v.items():
        if ver in TIER and i not in kills:
            n = 0
            for b in canon[i]:
                n |= 1 << b
            masks[n] = (i, TIER[ver])

    jobs = sorted((m, masks[m][1], masks[m][1], masks[m][1])
                  for m in frontier)
    jidx = {m: k for k, (m, _, _, _) in enumerate(jobs)}

    job_rows = [f"  ({m}, {w}, {h}, {dd})" for (m, w, h, dd) in jobs]
    inh_rows = [f"  ({m}, {jidx[M]})" for m, M in
                sorted(((int(m), M) for m, M in inheritance.items()),
                       key=lambda p: p[0])]

    jparts, jnames = subarrays(
        "colorFrontierJobs", "Array (Nat × Nat × Nat × Nat)", job_rows)
    iparts, inames = subarrays(
        "colorInheritance", "Array (Nat × Nat)", inh_rows)

    out = f"""/- AUTO-GENERATED by monotile/color_empty_lean_export.py.
Color empty frontier (65,250 locally-maximal empty masks, each with its
verdict tier's box dims — cake_lpr evidence in
monotile/color_frontier_verified.txt) and the 130,808 inheritance pairs
(profile mask, frontier job index). Do not edit by hand. -/
import LeanFlocq.AnyK3DColorEmpty

set_option maxRecDepth 1000000

namespace AnyK3D

{jparts}
def colorFrontierJobs : Array (Nat × Nat × Nat × Nat) := {jnames}

{iparts}
def colorInheritance : Array (Nat × Nat) := {inames}

end AnyK3D
"""
    path = f'{ROOT}/../lean-flocq/LeanFlocq/AnyK3DColorEmptyData.lean'
    with open(path, 'w') as f:
        f.write(out)
    print(f'wrote {path}: {len(jobs)} jobs, {len(inh_rows)} inheritance pairs')


if __name__ == '__main__':
    main()
