"""Export the unified color verdict table for the R3 coverage checker.

Merges the four verified tiers into one sorted array of
(profile-mask, tag) pairs:
  0 = periodic   (torus witness, AnyK3DColorPeriodicData*)
  1 = density    (density-kill, AnyK3DDensityKills*)
  2 = emptyF     (frontier box-UNSAT, cake-backed axiom)
  3 = emptyI     (inheritance via maskLe from a frontier mask)

Checks the four tiers partition the 414,079 canonical profiles, and that
canon 755 is in the density tier. Output: colorAllProfs in
lean-flocq/LeanFlocq/AnyK3DColorVerdictData.lean (<=1000-entry
sub-arrays appended, per the big-data operational notes).

Run: ./runpy.sh color_verdict_export.py
"""
import json

canon = json.load(open("color3d_canonical.json"))["canonical"]
cmasks = [sum(1 << e for e in p) for p in canon]
assert len(cmasks) == 414079

periodic = json.load(open("color_periodic_witnesses.json"))
density = json.load(open("color_density_kills.json"))
ef = json.load(open("color_empty_frontier.json"))

tag = {}
for w in periodic:
    tag[cmasks[w["i"]]] = 0
for k in density:
    tag[cmasks[k["i"]]] = 1
for m in ef["frontier"]:
    tag[m] = 2
for p in ef["inheritance"]:
    tag[int(p)] = 3

counts = [0, 0, 0, 0]
for t in tag.values():
    counts[t] += 1
print(f"tier counts: periodic {counts[0]}, density {counts[1]}, "
      f"emptyF {counts[2]}, emptyI {counts[3]}")
assert counts == [41824, 176197, 65250, 130808], counts
assert len(tag) == 414079, len(tag)
assert set(tag) == set(cmasks)
print("partition check OK: 414079 = 41824+176197+65250+130808")
print("canon 755 tag:", tag[cmasks[755]], "(want 1 = density)")
assert tag[cmasks[755]] == 1

rows = sorted(tag.items())
CH = 1000
chunks = [rows[i:i + CH] for i in range(0, len(rows), CH)]

out = ["/- AUTO-GENERATED by monotile/color_verdict_export.py.",
       "Unified verdict table for the color census coverage checker:",
       "414,079 canonical profiles with their verified tier tag",
       "(0 periodic, 1 density, 2 emptyF, 3 emptyI), sorted by profile.",
       "Do not edit by hand. -/",
       "namespace AnyK3D", ""]
for j, ch in enumerate(chunks):
    out.append(f"def colorAllProfs_{j} : Array (Nat × Nat) := #[")
    for p, t in ch:
        out.append(f"  ({p}, {t}),")
    out[-1] = out[-1].rstrip(",")
    out.append("]")
    out.append("")
out.append("def colorAllProfs : Array (Nat × Nat) :=")
out.append("  " + " ++ ".join(f"colorAllProfs_{j}" for j in range(len(chunks))))
out.append("")
out.append("end AnyK3D")
open("../lean-flocq/LeanFlocq/AnyK3DColorVerdictData.lean", "w").write(
    "\n".join(out))
print(f"wrote AnyK3DColorVerdictData.lean ({len(chunks)} chunks, "
      f"{len(rows)} rows)")
