"""Export density-lemma kill witnesses for all canonical color profiles.

For every canonical color profile with a deficient face-type class
(A pairs only into P, |A| > |P|), the density lemma (sharp form:
tileable needs (|A|-|P|)*L <= 6, proved in lean-flocq
ColorDensity.lean) kills every box of side L > 6/(|A|-|P|) — a slim
certificate that needs no SAT solver.

Outputs:
  color_density_kills.json — one record per deficient profile:
      {"i": canon index, "A": [...], "P": [...], "b": max tileable L}
  ../lean-flocq/LeanFlocq/AnyK3DDensityKills{j}.lean — chunked packed
      data (canon index, A/P masks, 84-bit profile) for kernel
      verification by AnyK3DDensityCheck (killOk + killOk_sound),
      one native_decide batch theorem per chunk.

Also prints the verdict-tier breakdown (how much of each emptyN tier
is density-covered).

Run:  ./runpy.sh color_density_export.py
"""
import itertools
import json
import os

os.environ.setdefault("ARENA_K", "4")

import arena2
import faceeq3d

N_CHUNKS = 12

CENSUS = json.load(open("faceeq3d_census.json"))
T2E = {}
for key, ei in CENSUS["triple_to_eq"].items():
    ax, o1, o2 = map(int, key.split(","))
    T2E[(ax, o1, o2)] = ei

WORLDFACE = [(ax, s) for ax in range(3) for s in (1, -1)]
SIGMA = []
for o in range(24):
    row = []
    for ax, s in WORLDFACE:
        j = next(i for i, p in enumerate(arena2.PTS)
                 if p[ax] == s * arena2.K)
        row.append(faceeq3d.face_and_coords(arena2.PERMINV[o][j])[0])
    SIGMA.append(row)

TRIPLES = []
for ax in range(3):
    for o1 in range(24):
        for o2 in range(24):
            TRIPLES.append((ax, o1, o2,
                            SIGMA[o1][2 * ax], SIGMA[o2][2 * ax + 1]))


def pair_relation(prof):
    held = set(prof)
    pair = [[False] * 6 for _ in range(6)]
    for ax, o1, o2, g, h in TRIPLES:
        if T2E[(ax, o1, o2)] in held:
            pair[g][h] = True
    return pair


def deficiency_witness(prof):
    """Best (smallest-bound) (A, P, bound), or None.

    P is the symmetrized partner set (rows and columns): an A-face
    pointing either way across an adjacency must land its partner in P.
    This is exactly the condition the Lean density instance checks
    (pairSymOf, the symmetric closure of the induced pair relation);
    row-only partners would be unsound for non-symmetric relations."""
    pair = pair_relation(prof)
    best = None
    for r in range(1, 6):
        for A in itertools.combinations(range(6), r):
            partners = set()
            for g in A:
                partners |= {h for h in range(6) if pair[g][h]}
                partners |= {h for h in range(6) if pair[h][g]}
            if not partners:
                continue
            if len(A) <= len(partners):
                continue
            b = 6 // (len(A) - len(partners))
            if best is None or b < best[2]:
                best = (sorted(A), sorted(partners), b)
    return best


def pack_profile(prof):
    n = 0
    for i in prof:
        n |= 1 << i
    return n


def mask(types):
    m = 0
    for t in types:
        m |= 1 << t
    return m


def main():
    canonical = json.load(open("color3d_canonical.json"))["canonical"]
    verdicts = {}
    for line in open("classify_color.jsonl"):
        r = json.loads(line)
        verdicts[r["i"]] = r["verdict"]

    kills = []
    for ci, prof in enumerate(canonical):
        w = deficiency_witness(prof)
        if w is None:
            continue
        A, P, b = w
        kills.append({
            "i": ci, "A": A, "P": P, "b": b,
            "prof": pack_profile(prof),
            "idMask": ci * 4096 + mask(A) + (mask(P) << 6),
        })
    print(f"density kills: {len(kills)} / {len(canonical)}")

    # verdict-tier breakdown
    tiers = {}
    for k in kills:
        v = verdicts.get(k["i"], "?")
        tiers[v] = tiers.get(v, 0) + 1
    print("kills by verdict tier:", sorted(tiers.items()))

    with open("color_density_kills.json", "w") as f:
        json.dump([{k: kk for k, kk in rec.items()
                    if k not in ("prof", "idMask")} for rec in kills], f)

    # Lean export, chunked (sub-arrays of <=1000 entries to bound
    # elaborator recursion on the literals)
    per = (len(kills) + N_CHUNKS - 1) // N_CHUNKS
    SUB = 1000
    for j in range(N_CHUNKS):
        chunk = kills[j * per:(j + 1) * per]
        subs = [chunk[k:k + SUB] for k in range(0, len(chunk), SUB)]
        parts = []
        for si, sub in enumerate(subs):
            rows = ",\n".join(f"  ({k['idMask']}, {k['prof']})" for k in sub)
            parts.append(f"def killsData{j}_{si} : Array (Nat × Nat) := #[\n{rows}\n]\n")
        names = " ++ ".join(f"killsData{j}_{si}" for si in range(len(subs)))
        body = "\n".join(parts)
        out = f"""/- AUTO-GENERATED by monotile/color_density_export.py.
Density-lemma kill witnesses, chunk {j} of {N_CHUNKS}
(canonical indices {chunk[0]['i']}..{chunk[-1]['i']} of
monotile/color3d_canonical.json). Each entry packs
(idMask = canon_index * 4096 + A_mask + P_mask * 64, 84-bit profile).
Do not edit by hand. -/
import LeanFlocq.AnyK3DDensityCheck

set_option maxRecDepth 1000000

namespace AnyK3D

{body}
def killsData{j} : Array (Nat × Nat) := {names}

theorem killsData{j}_verified :
    killsData{j}.all (fun x => killOk x.2 (x.1 % 4096)) = true := by
  native_decide

set_option maxHeartbeats 800000 in
theorem killsData{j}_empty : ∀ x ∈ killsData{j},
    ¬ ∃ ω, IsTiling (relOfHeld (heldOfNat x.2)) ω := by
  intro x hx
  exact killOk_sound _ _
    (Array.all_eq_true_iff_forall_mem.mp killsData{j}_verified x hx)

end AnyK3D
"""
        path = f"../lean-flocq/LeanFlocq/AnyK3DDensityKills{j}.lean"
        with open(path, "w") as f:
            f.write(out)
    print(f"wrote {N_CHUNKS} lean chunk files")


if __name__ == "__main__":
    main()
