"""Export the 34 straggler cube-and-conquer trees as a Lean file
(lean-flocq/LeanFlocq/AnyK3DStragTrees.lean), the CubeCover pattern:
per straggler, preorder shape (T=internal, F=leaf) from
cube_strag34_done.jsonl leaves over the phase-bit split order; one
cake_lpr-backed axiom for all leaves; per-straggler Unsat theorems.

Round-trip checked: parseTree order shape reproduces exactly the
checkpoint leaf set (mirrors export_tree.py).

Run:  ./runpy.sh export_strag_trees.py
"""
import json

ROOT = '/home/bepis/prog/verus-cad/monotile'
LEAN = '/home/bepis/prog/verus-cad/lean-flocq/LeanFlocq/AnyK3DStragTrees.lean'
TIER_BOX = {"empty4": 4, "empty5": 5, "empty6": 6}

strags = [r for r in json.load(open(f'{ROOT}/frontier_tiers.json'))
          if r['verdict'] in TIER_BOX]
cubes_by_ci = {}
for line in open(f'{ROOT}/cube_strag34_done.jsonl'):
    r = json.loads(line)
    if r['verdict'] == 'UNSAT':
        cubes_by_ci.setdefault(r['i'], []).append(r['cube'])

def shape_of(cubes, t):
    """Preorder shape over the phase-bit order for box t^3."""
    nc = t * t * t
    # python split order, 1-based: nbase + ci*5 + k + 1
    order = [nc * 24 + ci * 5 + k + 1 for ci in range(nc) for k in range(5)]
    pos = {v: i for i, v in enumerate(order)}

    def to_path(cube):
        d = sorted(cube, key=lambda L: pos[abs(L)])
        for i, L in enumerate(d):
            assert abs(L) == order[i], f"cube not an order-prefix: {cube}"
        return [L > 0 for L in d]

    paths = [to_path(c) for c in cubes]

    def build(ps):
        if len(ps) == 1 and ps[0] == []:
            return [False]
        assert all(p for p in ps), "not prefix-free"
        lo = [p[1:] for p in ps if not p[0]]
        hi = [p[1:] for p in ps if p[0]]
        assert len(lo) + len(hi) == len(ps)
        return [True] + build(lo) + build(hi)

    shape = build(paths)

    def parse(sh, depth, i):
        if sh[i]:
            lo, i1 = parse(sh, depth + 1, i + 1)
            hi, i2 = parse(sh, depth + 1, i1)
            return ([[(depth, False)] + c for c in lo] +
                    [[(depth, True)] + c for c in hi], i2)
        return ([[]], i + 1)

    recovered, ni = parse(shape, 0, 0)
    assert ni == len(shape)
    orig = {tuple(p) for p in paths}
    rec = {tuple(order[b] > 0 and 1 or 0 for (d, b) in c) for c in recovered}
    rec = {tuple(1 if b else 0 for (d, b) in c) for c in recovered}
    assert orig == rec, f"ROUND-TRIP MISMATCH {len(orig)} vs {len(rec)}"
    return ''.join('T' if b else 'F' for b in shape), len(paths)

entries = []
for rec in strags:
    ci, verdict, mask = rec['i'], rec['verdict'], rec['mask']
    t = TIER_BOX[verdict]
    shape, nleaves = shape_of(cubes_by_ci[ci], t)
    entries.append((ci, mask, t, shape, nleaves))
    print(f"  straggler {ci} ({verdict}): {nleaves} leaves, "
          f"{len(shape)} tokens", flush=True)

defs = []
axioms = []
for j, (ci, mask, t, shape, nleaves) in enumerate(entries):
    nc = t * t * t
    defs.append(f"""/-- straggler {ci}: mask {mask}, box {t}^3 ({nleaves} leaves). -/
def stragMask{j} : Nat := {mask}
def stragDim{j} : Nat := {t}
def stragShape{j} : String :=
  "{shape}"
def stragTree{j} : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder {nc}) (stragShape{j}.data.map (· == 'T'))""")
    axioms.append(f"""axiom stragLeafUnsat{j} :
    ∀ cube ∈ stragTree{j}.cubes,
      (emptyCNFX stragMask{j} stragDim{j} stragDim{j} stragDim{j} ++ cube).Unsat

/-- straggler {ci} is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat{j} :
    (emptyCNFX stragMask{j} stragDim{j} stragDim{j} stragDim{j}).Unsat :=
  stragTree{j}.unsat _ stragLeafUnsat{j}

/-- straggler {ci} has no space tiling (emptyX_sound). -/
theorem stragEmpty{j} : ¬ ∃ ω, IsTiling (relOfMask stragMask{j}) ω :=
  emptyX_sound (by norm_num [stragDim{j}] : 0 < stragDim{j})
    (by norm_num [stragDim{j}]) stragUnsat{j}""")

lean = f'''/- AUTO-GENERATED by monotile/export_strag_trees.py from
   cube_strag34_done.jsonl — do not edit by hand.

   The 34 straggler maximal-empty masks' cube-and-conquer trees
   (phase-bit splits, leaves round-trip checked against the checkpoint).
   Per-leaf UNSAT is the cake_lpr-trusted axiom; covers are kernel-proven
   (CubeCover.VTree.covers). -/
import LeanFlocq.CubeCover
import LeanFlocq.AnyK3DEmptyEnc

open AnyK3D Std.Sat

namespace AnyK3D

/-- The phase-bit split order for an nc-cell box (Lean 0-based vars:
bVar nc ci k = nc*24 + ci*5 + k). -/
def phaseOrder (nc : Nat) : List Nat :=
  (List.range nc).flatMap fun ci => (List.range 5).map fun k =>
    nc * 24 + ci * 5 + k

{chr(10).join(defs)}

/-! ## the cake_lpr-trusted leaf facts (see stream_verify pattern;
verification in monotile/verify_strag_leaves.py) -/

{chr(10).join(axioms)}

end AnyK3D
'''
open(LEAN, 'w').write(lean)
print(f"wrote {LEAN}: {len(entries)} stragglers")
