"""Generate viz/data.js: the 84 color equations + decoration presets
(canon 755's extracted decoration if present).

Run:  ./runpy.sh viz/gen_data.py
"""
import json
import os

census = json.load(open("faceeq3d_census.json"))
eqs = [{"g": g, "h": h, "tau": tau} for g, h, tau in census["equations"]]

presets = []
if os.path.exists("color_755_decoration.json"):
    d = json.load(open("color_755_decoration.json"))
    presets.append({
        "name": "canon 755 (the finalist)",
        "K": d["K"], "T": d["T"],
        "cells": d["cells"], "faces": d["faces"],
        "profile": d["profile"],
    })

out = ("// AUTO-GENERATED by viz/gen_data.py — do not edit\n"
       "const EQUATIONS = " + json.dumps(eqs) + ";\n"
       "const PRESETS = " + json.dumps(presets) + ";\n")
open("viz/data.js", "w").write(out)
print(f"wrote viz/data.js: {len(eqs)} equations, {len(presets)} presets")
